name: "help.md generator"
description: "Generate help.md and push to GitHub"
author: tsubasaogawa

inputs:
  binary_path:
    description: "Target binary path (ex. /bin/cat)"
    required: true
  cmd:
    description: "Additional commands for the binary (ex. --help)"
    required: false
    default: "--help"
  redirects:
    description: "Command redirects"
    required: false
    default: "2>&1"
  title:
    description: "Markdown title"
    required: false
    default: "Help"
  artifact_path:
    description: "Path of a generated artifact"
    required: false
    default: "help.md"
  working_directory:
    description: "Working directory (to repository)"
    required: false
    default: "."
  footer:
    description: "Document footer"
    required: false
    default: ""

outputs:
  committed:
    description: "1 if file is committed"
    value: ${{ steps.push.outputs.committed }}

runs:
  using: "composite"
  steps:
    - name: Validations
      run: |
        set -e
        which "${{ inputs.binary_path }}"
        test "${{ inputs.title }}" != ""
        test "${{ inputs.artifact_path }}" != ""
        test -e "${{ inputs.working_directory }}"
      shell: bash
    - name: Run binary
      run: ${{ inputs.binary_path }} ${{ inputs.cmd }} > ${{ runner.temp }}/${{ github.run_number }}.log ${{ inputs.redirects }}
      shell: bash
    - name: Generate md
      run: |
        set -e
        # Create a directory if does not exist
        TARGET_DIR="$(dirname ${{ inputs.artifact_path }})"
        test -e $TARGET_DIR || mkdir -p $TARGET_DIR

        sed \
          -e 's/```//g' \
          -e '1i # ${{ inputs.title }}' \
          -e '1i \\' \
          -e '1i ```' \
          -e '$a ```' \
          -e '$a \\' \
          ${{ runner.temp }}/${{ github.run_number }}.log > ${{ inputs.artifact_path }}

        ! echo ${{ inputs.footer }} | grep -e '^[[:space:]]*$' || exit 0
        sed \
          -i.old \
          -e '$a ---' \
          -e '$a ${{ inputs.footer }}' \
          -e '$a \\' \
          ${{ inputs.artifact_path }}
      shell: bash
      working-directory: ${{ inputs.working_directory }}
    - name: Push
      id: push
      env:
        GHA_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
        GHA_NAME: "github-actions[bot]"
      run: |
        set -e
        git config --local user.email $GHA_EMAIL
        git config --local user.name $GHA_NAME
        git add ${{ inputs.artifact_path }}
        if ! git commit -m 'Update ${{ inputs.artifact_path }}'; then
          echo "committed=0" >> $GITHUB_OUTPUT
          exit 0
        fi
        echo "committed=1" >> $GITHUB_OUTPUT
        git push
      shell: bash

branding:
  icon: "file"
  color: "purple"
